# Develop Environments for ODM2DataSharingPortal
name: ODM2DataSharingPortal
channels:
    - conda-forge
    - defaults

dependencies:
    - python >=3.10.4 

    - boto3
    - coverage >=5.5
    - google-api-python-client >=2.12.0
    - hs_restclient >=1.3.7  # https://github.com/hydroshare/hs_restclient
    - markdown >=3.3.4
    - pandas >=1.3
    - psycopg2 >=2.9.1
    - python-crontab >=2.5.1
    - sqlalchemy >=1.4.0,<2.0

    # Dev tools: Language Server Protocol (LSP) (Optional), for...
      # code navigation + hover suggestions + linters + autocompletion + rename
    - python-lsp-server >=1.6 # LSP extension for Python (pylsp), including:
      # Rope for Completions and renaming
      # Pyflakes linter to detect various errors
      # McCabe linter for complexity checking
      # pycodestyle linter for style checking
      # pydocstyle linter for docstring style checking (disabled by default)
      # autopep8 for code formatting
      # YAPF for code formatting (preferred over autopep8)
      # flake8 for error checking (disabled by default)
      # pylint for code linting (disabled by default)
    - pylsp-mypy  # MyPy type checking for Python >=3.7.

    # package management
    - conda
    - conda-build
    - conda-libmamba-solver
    - pip

    - pip:
        - django==3.2.16
        - djangorestframework
        - django-debug-toolbar 
        - django-widget-tweaks
        - django-admin-select2 
        - django-discover-runner
        - django-reset-migrations
        - django-webtest 
        - django-cprofile-middleware
        #used for unicode_compatiblity 
        #should confirm if this is still a dependency
        - django-utils-six
          #there was an error with recursive depth reintroduce in 2.4
        - django-formtools==2.3 

