# Develop Environments for ODM2DataSharingPortal
name: djangoenv_py36_dev
channels:
    - conda-forge
    - defaults

dependencies:
    # For ODM2DataSharing Portal release 0.11
    - python =3.6.*  # Installs 3.6.13
    # - Django =1.11.29

    # # Other Requirements
    - coverage >=5.0.4
    - google-api-python-client >=1.6.7
    - hs_restclient >=1.2.10
    - Markdown >=3.3.3
    - oauthlib >=2.0.*
    - pandas >=0.23.4
    - psycopg2 >=2.7.7
    - python-crontab >=2.2.8 
    - sqlparse >=0.3.1
    - unicodecsv >=0.14.1
    - waitress >=1.4.3
    - WebOb >=1.6.2
    - WebTest >=2.0.23
    # - requests ==2.25.1  # with django==1.11.29
    # - six ==1.15.0  # with django==1.11.29


    # Dev tools
    - python-language-server

    # package management
    - conda
    - conda-build
    - pip

    # Dependencies not available on conda-forge
    - pip:
        # - beautifulsoup4 =4.9.3  # with django==1.11.29
        # - codegen >=1.0  # with django==1.11.29
        - django ==1.11.29
        - django-admin-select2 >=1.0.1
        - django-debug-toolbar >=1.11.1
        - django-discover-runner >=1.0
        - django-reset-migrations >=0.3.1
        - django-webtest >=1.8.0
        - django-widget-tweaks >=1.4.1
        - djangorestframework >=3.9.1
        - patterns >=0.3  # necessary? Last updated in 2014
        # - enum  # superceeded by Python >3.4 standard library
