# Develop Environments for ODM2DataSharingPortal
name: djangoenv_py27_dev
channels:
    - conda-forge
    - defaults

dependencies:
    # For ODM2DataSharing Portal release 0.11
    - python =2.7*
    # - Django =1.11.29

    # Other Requirements
    - coverage==4.2
    - Markdown==2.6.7
    - psycopg2==2.7.1
    - six==1.10.0
    - sqlparse==0.2.2
    - waitress==1.4.3
    - WebOb==1.6.2
    - requests==2.20.0
    - unicodecsv==0.14.1
    - oauthlib==2.0.*
    - google-api-python-client==1.6.7
    - pandas==0.23.4

    # Dev tools
    - python-language-server

    # package management
    - conda
    - conda-build
    - pip
    - pip:
        - beautifulsoup4==4.5.1
        - codegen==1.0
        - Django==1.11.28
        - django-debug-toolbar==1.6
        - django-discover-runner==1.0
        - django-webtest==1.8.0
        - django-widget-tweaks==1.4.1
        - djangorestframework==3.9.1
        - django-reset-migrations==0.3.1
        - django-admin-select2==1.0.1
        - hs_restclient==1.2.10
        - patterns==0.3
        - python-crontab==2.2.8
        - enum==0.4.6
        - WebTest==2.0.23
