# Develop Environments for ODM2DataSharingPortal
name: ODM2DataSharingPortal
channels:
    - conda-forge
    - defaults

dependencies:
    - python =3.9.* 

    - coverage >=5.5
    - google-api-python-client >=2.12.0
    - hs_restclient >=1.3.7  # https://github.com/hydroshare/hs_restclient
    - markdown >=3.3.4
    - pandas >=1.3
    - psycopg2 >=2.9.1
    - python-crontab >=2.5.1
    - sqlalchemy >=1.4.0 

    #django
    #additional django dependencies installed with pip
    - django ==3.2.*
    - djangorestframework
    - django-debug-toolbar 
    - django-widget-tweaks

    # Dev tools
    - python-language-server

    # package management
    - conda
    - conda-build
    - pip

    - pip:
        - django-admin-select2 
        - django-discover-runner
        - django-reset-migrations
        - django-webtest 
        - django-cprofile-middleware
        #used for unicode_compatiblity 
        #should confirm if this is still a dependency
        - django-utils-six